/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WarrantyRouteImport } from './routes/warranty'
import { Route as ChamCongRouteImport } from './routes/cham-cong'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UUserLayoutRouteImport } from './routes/u/_userLayout'
import { Route as EEmployeeLayoutRouteImport } from './routes/e/_employeeLayout'
import { Route as AdminReportLayoutRouteImport } from './routes/admin/_reportLayout'
import { Route as UUserLayoutLoginRouteImport } from './routes/u/_userLayout/login'
import { Route as UUserLayoutDashboardLayoutRouteImport } from './routes/u/_userLayout/_dashboardLayout'
import { Route as EEmployeeLayoutLoginRouteImport } from './routes/e/_employeeLayout/login'
import { Route as EEmployeeLayoutDashboardLayoutRouteImport } from './routes/e/_employeeLayout/_dashboardLayout'
import { Route as AdminReportLayoutKiotvietRouteImport } from './routes/admin/_reportLayout/kiotviet'
import { Route as AdminReportLayoutDahahiRouteImport } from './routes/admin/_reportLayout/dahahi'
import { Route as UUserLayoutDashboardLayoutIndexRouteImport } from './routes/u/_userLayout/_dashboardLayout/index'
import { Route as EEmployeeLayoutDashboardLayoutIndexRouteImport } from './routes/e/_employeeLayout/_dashboardLayout/index'
import { Route as UUserLayoutDashboardLayoutShiftSlotsRouteImport } from './routes/u/_userLayout/_dashboardLayout/shift-slots'
import { Route as UUserLayoutDashboardLayoutShiftSlotTypesRouteImport } from './routes/u/_userLayout/_dashboardLayout/shift-slot-types'
import { Route as UUserLayoutDashboardLayoutSettingsRouteImport } from './routes/u/_userLayout/_dashboardLayout/settings'
import { Route as UUserLayoutDashboardLayoutLeaveRequestsRouteImport } from './routes/u/_userLayout/_dashboardLayout/leave-requests'
import { Route as UUserLayoutDashboardLayoutDepartmentsRouteImport } from './routes/u/_userLayout/_dashboardLayout/departments'
import { Route as UUserLayoutDashboardLayoutBranchsRouteImport } from './routes/u/_userLayout/_dashboardLayout/branchs'
import { Route as EEmployeeLayoutDashboardLayoutTasksRouteImport } from './routes/e/_employeeLayout/_dashboardLayout/tasks'
import { Route as EEmployeeLayoutDashboardLayoutShiftSlotsRouteImport } from './routes/e/_employeeLayout/_dashboardLayout/shift-slots'
import { Route as EEmployeeLayoutDashboardLayoutSettingsRouteImport } from './routes/e/_employeeLayout/_dashboardLayout/settings'
import { Route as EEmployeeLayoutDashboardLayoutLeaveRequestsRouteImport } from './routes/e/_employeeLayout/_dashboardLayout/leave-requests'
import { Route as EEmployeeLayoutDashboardLayoutChangeShiftRequestsRouteImport } from './routes/e/_employeeLayout/_dashboardLayout/change-shift-requests'
import { Route as UUserLayoutDashboardLayoutUserAdminsIndexRouteImport } from './routes/u/_userLayout/_dashboardLayout/user-admins/index'
import { Route as UUserLayoutDashboardLayoutTasksIndexRouteImport } from './routes/u/_userLayout/_dashboardLayout/tasks/index'
import { Route as UUserLayoutDashboardLayoutEmployeesIndexRouteImport } from './routes/u/_userLayout/_dashboardLayout/employees/index'
import { Route as UUserLayoutDashboardLayoutUserAdminsIdRouteImport } from './routes/u/_userLayout/_dashboardLayout/user-admins/$id'
import { Route as UUserLayoutDashboardLayoutTasksPendingApprovelRouteImport } from './routes/u/_userLayout/_dashboardLayout/tasks/pending-approvel'
import { Route as UUserLayoutDashboardLayoutEmployeesIdRouteImport } from './routes/u/_userLayout/_dashboardLayout/employees/$id'

const WarrantyRoute = WarrantyRouteImport.update({
  id: '/warranty',
  path: '/warranty',
  getParentRoute: () => rootRouteImport,
} as any)
const ChamCongRoute = ChamCongRouteImport.update({
  id: '/cham-cong',
  path: '/cham-cong',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UUserLayoutRoute = UUserLayoutRouteImport.update({
  id: '/_userLayout',
  getParentRoute: () => URoute,
} as any)
const EEmployeeLayoutRoute = EEmployeeLayoutRouteImport.update({
  id: '/_employeeLayout',
  getParentRoute: () => ERoute,
} as any)
const AdminReportLayoutRoute = AdminReportLayoutRouteImport.update({
  id: '/_reportLayout',
  getParentRoute: () => AdminRoute,
} as any)
const UUserLayoutLoginRoute = UUserLayoutLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => UUserLayoutRoute,
} as any)
const UUserLayoutDashboardLayoutRoute =
  UUserLayoutDashboardLayoutRouteImport.update({
    id: '/_dashboardLayout',
    getParentRoute: () => UUserLayoutRoute,
  } as any)
const EEmployeeLayoutLoginRoute = EEmployeeLayoutLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => EEmployeeLayoutRoute,
} as any)
const EEmployeeLayoutDashboardLayoutRoute =
  EEmployeeLayoutDashboardLayoutRouteImport.update({
    id: '/_dashboardLayout',
    getParentRoute: () => EEmployeeLayoutRoute,
  } as any)
const AdminReportLayoutKiotvietRoute =
  AdminReportLayoutKiotvietRouteImport.update({
    id: '/kiotviet',
    path: '/kiotviet',
    getParentRoute: () => AdminReportLayoutRoute,
  } as any)
const AdminReportLayoutDahahiRoute = AdminReportLayoutDahahiRouteImport.update({
  id: '/dahahi',
  path: '/dahahi',
  getParentRoute: () => AdminReportLayoutRoute,
} as any)
const UUserLayoutDashboardLayoutIndexRoute =
  UUserLayoutDashboardLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => UUserLayoutDashboardLayoutRoute,
  } as any)
const EEmployeeLayoutDashboardLayoutIndexRoute =
  EEmployeeLayoutDashboardLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => EEmployeeLayoutDashboardLayoutRoute,
  } as any)
const UUserLayoutDashboardLayoutShiftSlotsRoute =
  UUserLayoutDashboardLayoutShiftSlotsRouteImport.update({
    id: '/shift-slots',
    path: '/shift-slots',
    getParentRoute: () => UUserLayoutDashboardLayoutRoute,
  } as any)
const UUserLayoutDashboardLayoutShiftSlotTypesRoute =
  UUserLayoutDashboardLayoutShiftSlotTypesRouteImport.update({
    id: '/shift-slot-types',
    path: '/shift-slot-types',
    getParentRoute: () => UUserLayoutDashboardLayoutRoute,
  } as any)
const UUserLayoutDashboardLayoutSettingsRoute =
  UUserLayoutDashboardLayoutSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => UUserLayoutDashboardLayoutRoute,
  } as any)
const UUserLayoutDashboardLayoutLeaveRequestsRoute =
  UUserLayoutDashboardLayoutLeaveRequestsRouteImport.update({
    id: '/leave-requests',
    path: '/leave-requests',
    getParentRoute: () => UUserLayoutDashboardLayoutRoute,
  } as any)
const UUserLayoutDashboardLayoutDepartmentsRoute =
  UUserLayoutDashboardLayoutDepartmentsRouteImport.update({
    id: '/departments',
    path: '/departments',
    getParentRoute: () => UUserLayoutDashboardLayoutRoute,
  } as any)
const UUserLayoutDashboardLayoutBranchsRoute =
  UUserLayoutDashboardLayoutBranchsRouteImport.update({
    id: '/branchs',
    path: '/branchs',
    getParentRoute: () => UUserLayoutDashboardLayoutRoute,
  } as any)
const EEmployeeLayoutDashboardLayoutTasksRoute =
  EEmployeeLayoutDashboardLayoutTasksRouteImport.update({
    id: '/tasks',
    path: '/tasks',
    getParentRoute: () => EEmployeeLayoutDashboardLayoutRoute,
  } as any)
const EEmployeeLayoutDashboardLayoutShiftSlotsRoute =
  EEmployeeLayoutDashboardLayoutShiftSlotsRouteImport.update({
    id: '/shift-slots',
    path: '/shift-slots',
    getParentRoute: () => EEmployeeLayoutDashboardLayoutRoute,
  } as any)
const EEmployeeLayoutDashboardLayoutSettingsRoute =
  EEmployeeLayoutDashboardLayoutSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => EEmployeeLayoutDashboardLayoutRoute,
  } as any)
const EEmployeeLayoutDashboardLayoutLeaveRequestsRoute =
  EEmployeeLayoutDashboardLayoutLeaveRequestsRouteImport.update({
    id: '/leave-requests',
    path: '/leave-requests',
    getParentRoute: () => EEmployeeLayoutDashboardLayoutRoute,
  } as any)
const EEmployeeLayoutDashboardLayoutChangeShiftRequestsRoute =
  EEmployeeLayoutDashboardLayoutChangeShiftRequestsRouteImport.update({
    id: '/change-shift-requests',
    path: '/change-shift-requests',
    getParentRoute: () => EEmployeeLayoutDashboardLayoutRoute,
  } as any)
const UUserLayoutDashboardLayoutUserAdminsIndexRoute =
  UUserLayoutDashboardLayoutUserAdminsIndexRouteImport.update({
    id: '/user-admins/',
    path: '/user-admins/',
    getParentRoute: () => UUserLayoutDashboardLayoutRoute,
  } as any)
const UUserLayoutDashboardLayoutTasksIndexRoute =
  UUserLayoutDashboardLayoutTasksIndexRouteImport.update({
    id: '/tasks/',
    path: '/tasks/',
    getParentRoute: () => UUserLayoutDashboardLayoutRoute,
  } as any)
const UUserLayoutDashboardLayoutEmployeesIndexRoute =
  UUserLayoutDashboardLayoutEmployeesIndexRouteImport.update({
    id: '/employees/',
    path: '/employees/',
    getParentRoute: () => UUserLayoutDashboardLayoutRoute,
  } as any)
const UUserLayoutDashboardLayoutUserAdminsIdRoute =
  UUserLayoutDashboardLayoutUserAdminsIdRouteImport.update({
    id: '/user-admins/$id',
    path: '/user-admins/$id',
    getParentRoute: () => UUserLayoutDashboardLayoutRoute,
  } as any)
const UUserLayoutDashboardLayoutTasksPendingApprovelRoute =
  UUserLayoutDashboardLayoutTasksPendingApprovelRouteImport.update({
    id: '/tasks/pending-approvel',
    path: '/tasks/pending-approvel',
    getParentRoute: () => UUserLayoutDashboardLayoutRoute,
  } as any)
const UUserLayoutDashboardLayoutEmployeesIdRoute =
  UUserLayoutDashboardLayoutEmployeesIdRouteImport.update({
    id: '/employees/$id',
    path: '/employees/$id',
    getParentRoute: () => UUserLayoutDashboardLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cham-cong': typeof ChamCongRoute
  '/warranty': typeof WarrantyRoute
  '/admin': typeof AdminReportLayoutRouteWithChildren
  '/e': typeof EEmployeeLayoutDashboardLayoutRouteWithChildren
  '/u': typeof UUserLayoutDashboardLayoutRouteWithChildren
  '/admin/dahahi': typeof AdminReportLayoutDahahiRoute
  '/admin/kiotviet': typeof AdminReportLayoutKiotvietRoute
  '/e/login': typeof EEmployeeLayoutLoginRoute
  '/u/login': typeof UUserLayoutLoginRoute
  '/e/change-shift-requests': typeof EEmployeeLayoutDashboardLayoutChangeShiftRequestsRoute
  '/e/leave-requests': typeof EEmployeeLayoutDashboardLayoutLeaveRequestsRoute
  '/e/settings': typeof EEmployeeLayoutDashboardLayoutSettingsRoute
  '/e/shift-slots': typeof EEmployeeLayoutDashboardLayoutShiftSlotsRoute
  '/e/tasks': typeof EEmployeeLayoutDashboardLayoutTasksRoute
  '/u/branchs': typeof UUserLayoutDashboardLayoutBranchsRoute
  '/u/departments': typeof UUserLayoutDashboardLayoutDepartmentsRoute
  '/u/leave-requests': typeof UUserLayoutDashboardLayoutLeaveRequestsRoute
  '/u/settings': typeof UUserLayoutDashboardLayoutSettingsRoute
  '/u/shift-slot-types': typeof UUserLayoutDashboardLayoutShiftSlotTypesRoute
  '/u/shift-slots': typeof UUserLayoutDashboardLayoutShiftSlotsRoute
  '/e/': typeof EEmployeeLayoutDashboardLayoutIndexRoute
  '/u/': typeof UUserLayoutDashboardLayoutIndexRoute
  '/u/employees/$id': typeof UUserLayoutDashboardLayoutEmployeesIdRoute
  '/u/tasks/pending-approvel': typeof UUserLayoutDashboardLayoutTasksPendingApprovelRoute
  '/u/user-admins/$id': typeof UUserLayoutDashboardLayoutUserAdminsIdRoute
  '/u/employees': typeof UUserLayoutDashboardLayoutEmployeesIndexRoute
  '/u/tasks': typeof UUserLayoutDashboardLayoutTasksIndexRoute
  '/u/user-admins': typeof UUserLayoutDashboardLayoutUserAdminsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cham-cong': typeof ChamCongRoute
  '/warranty': typeof WarrantyRoute
  '/admin': typeof AdminReportLayoutRouteWithChildren
  '/e': typeof EEmployeeLayoutDashboardLayoutIndexRoute
  '/u': typeof UUserLayoutDashboardLayoutIndexRoute
  '/admin/dahahi': typeof AdminReportLayoutDahahiRoute
  '/admin/kiotviet': typeof AdminReportLayoutKiotvietRoute
  '/e/login': typeof EEmployeeLayoutLoginRoute
  '/u/login': typeof UUserLayoutLoginRoute
  '/e/change-shift-requests': typeof EEmployeeLayoutDashboardLayoutChangeShiftRequestsRoute
  '/e/leave-requests': typeof EEmployeeLayoutDashboardLayoutLeaveRequestsRoute
  '/e/settings': typeof EEmployeeLayoutDashboardLayoutSettingsRoute
  '/e/shift-slots': typeof EEmployeeLayoutDashboardLayoutShiftSlotsRoute
  '/e/tasks': typeof EEmployeeLayoutDashboardLayoutTasksRoute
  '/u/branchs': typeof UUserLayoutDashboardLayoutBranchsRoute
  '/u/departments': typeof UUserLayoutDashboardLayoutDepartmentsRoute
  '/u/leave-requests': typeof UUserLayoutDashboardLayoutLeaveRequestsRoute
  '/u/settings': typeof UUserLayoutDashboardLayoutSettingsRoute
  '/u/shift-slot-types': typeof UUserLayoutDashboardLayoutShiftSlotTypesRoute
  '/u/shift-slots': typeof UUserLayoutDashboardLayoutShiftSlotsRoute
  '/u/employees/$id': typeof UUserLayoutDashboardLayoutEmployeesIdRoute
  '/u/tasks/pending-approvel': typeof UUserLayoutDashboardLayoutTasksPendingApprovelRoute
  '/u/user-admins/$id': typeof UUserLayoutDashboardLayoutUserAdminsIdRoute
  '/u/employees': typeof UUserLayoutDashboardLayoutEmployeesIndexRoute
  '/u/tasks': typeof UUserLayoutDashboardLayoutTasksIndexRoute
  '/u/user-admins': typeof UUserLayoutDashboardLayoutUserAdminsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cham-cong': typeof ChamCongRoute
  '/warranty': typeof WarrantyRoute
  '/admin/_reportLayout': typeof AdminReportLayoutRouteWithChildren
  '/e/_employeeLayout': typeof EEmployeeLayoutRouteWithChildren
  '/u/_userLayout': typeof UUserLayoutRouteWithChildren
  '/admin/_reportLayout/dahahi': typeof AdminReportLayoutDahahiRoute
  '/admin/_reportLayout/kiotviet': typeof AdminReportLayoutKiotvietRoute
  '/e/_employeeLayout/_dashboardLayout': typeof EEmployeeLayoutDashboardLayoutRouteWithChildren
  '/e/_employeeLayout/login': typeof EEmployeeLayoutLoginRoute
  '/u/_userLayout/_dashboardLayout': typeof UUserLayoutDashboardLayoutRouteWithChildren
  '/u/_userLayout/login': typeof UUserLayoutLoginRoute
  '/e/_employeeLayout/_dashboardLayout/change-shift-requests': typeof EEmployeeLayoutDashboardLayoutChangeShiftRequestsRoute
  '/e/_employeeLayout/_dashboardLayout/leave-requests': typeof EEmployeeLayoutDashboardLayoutLeaveRequestsRoute
  '/e/_employeeLayout/_dashboardLayout/settings': typeof EEmployeeLayoutDashboardLayoutSettingsRoute
  '/e/_employeeLayout/_dashboardLayout/shift-slots': typeof EEmployeeLayoutDashboardLayoutShiftSlotsRoute
  '/e/_employeeLayout/_dashboardLayout/tasks': typeof EEmployeeLayoutDashboardLayoutTasksRoute
  '/u/_userLayout/_dashboardLayout/branchs': typeof UUserLayoutDashboardLayoutBranchsRoute
  '/u/_userLayout/_dashboardLayout/departments': typeof UUserLayoutDashboardLayoutDepartmentsRoute
  '/u/_userLayout/_dashboardLayout/leave-requests': typeof UUserLayoutDashboardLayoutLeaveRequestsRoute
  '/u/_userLayout/_dashboardLayout/settings': typeof UUserLayoutDashboardLayoutSettingsRoute
  '/u/_userLayout/_dashboardLayout/shift-slot-types': typeof UUserLayoutDashboardLayoutShiftSlotTypesRoute
  '/u/_userLayout/_dashboardLayout/shift-slots': typeof UUserLayoutDashboardLayoutShiftSlotsRoute
  '/e/_employeeLayout/_dashboardLayout/': typeof EEmployeeLayoutDashboardLayoutIndexRoute
  '/u/_userLayout/_dashboardLayout/': typeof UUserLayoutDashboardLayoutIndexRoute
  '/u/_userLayout/_dashboardLayout/employees/$id': typeof UUserLayoutDashboardLayoutEmployeesIdRoute
  '/u/_userLayout/_dashboardLayout/tasks/pending-approvel': typeof UUserLayoutDashboardLayoutTasksPendingApprovelRoute
  '/u/_userLayout/_dashboardLayout/user-admins/$id': typeof UUserLayoutDashboardLayoutUserAdminsIdRoute
  '/u/_userLayout/_dashboardLayout/employees/': typeof UUserLayoutDashboardLayoutEmployeesIndexRoute
  '/u/_userLayout/_dashboardLayout/tasks/': typeof UUserLayoutDashboardLayoutTasksIndexRoute
  '/u/_userLayout/_dashboardLayout/user-admins/': typeof UUserLayoutDashboardLayoutUserAdminsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cham-cong'
    | '/warranty'
    | '/admin'
    | '/e'
    | '/u'
    | '/admin/dahahi'
    | '/admin/kiotviet'
    | '/e/login'
    | '/u/login'
    | '/e/change-shift-requests'
    | '/e/leave-requests'
    | '/e/settings'
    | '/e/shift-slots'
    | '/e/tasks'
    | '/u/branchs'
    | '/u/departments'
    | '/u/leave-requests'
    | '/u/settings'
    | '/u/shift-slot-types'
    | '/u/shift-slots'
    | '/e/'
    | '/u/'
    | '/u/employees/$id'
    | '/u/tasks/pending-approvel'
    | '/u/user-admins/$id'
    | '/u/employees'
    | '/u/tasks'
    | '/u/user-admins'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cham-cong'
    | '/warranty'
    | '/admin'
    | '/e'
    | '/u'
    | '/admin/dahahi'
    | '/admin/kiotviet'
    | '/e/login'
    | '/u/login'
    | '/e/change-shift-requests'
    | '/e/leave-requests'
    | '/e/settings'
    | '/e/shift-slots'
    | '/e/tasks'
    | '/u/branchs'
    | '/u/departments'
    | '/u/leave-requests'
    | '/u/settings'
    | '/u/shift-slot-types'
    | '/u/shift-slots'
    | '/u/employees/$id'
    | '/u/tasks/pending-approvel'
    | '/u/user-admins/$id'
    | '/u/employees'
    | '/u/tasks'
    | '/u/user-admins'
  id:
    | '__root__'
    | '/'
    | '/cham-cong'
    | '/warranty'
    | '/admin/_reportLayout'
    | '/e/_employeeLayout'
    | '/u/_userLayout'
    | '/admin/_reportLayout/dahahi'
    | '/admin/_reportLayout/kiotviet'
    | '/e/_employeeLayout/_dashboardLayout'
    | '/e/_employeeLayout/login'
    | '/u/_userLayout/_dashboardLayout'
    | '/u/_userLayout/login'
    | '/e/_employeeLayout/_dashboardLayout/change-shift-requests'
    | '/e/_employeeLayout/_dashboardLayout/leave-requests'
    | '/e/_employeeLayout/_dashboardLayout/settings'
    | '/e/_employeeLayout/_dashboardLayout/shift-slots'
    | '/e/_employeeLayout/_dashboardLayout/tasks'
    | '/u/_userLayout/_dashboardLayout/branchs'
    | '/u/_userLayout/_dashboardLayout/departments'
    | '/u/_userLayout/_dashboardLayout/leave-requests'
    | '/u/_userLayout/_dashboardLayout/settings'
    | '/u/_userLayout/_dashboardLayout/shift-slot-types'
    | '/u/_userLayout/_dashboardLayout/shift-slots'
    | '/e/_employeeLayout/_dashboardLayout/'
    | '/u/_userLayout/_dashboardLayout/'
    | '/u/_userLayout/_dashboardLayout/employees/$id'
    | '/u/_userLayout/_dashboardLayout/tasks/pending-approvel'
    | '/u/_userLayout/_dashboardLayout/user-admins/$id'
    | '/u/_userLayout/_dashboardLayout/employees/'
    | '/u/_userLayout/_dashboardLayout/tasks/'
    | '/u/_userLayout/_dashboardLayout/user-admins/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChamCongRoute: typeof ChamCongRoute
  WarrantyRoute: typeof WarrantyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/warranty': {
      id: '/warranty'
      path: '/warranty'
      fullPath: '/warranty'
      preLoaderRoute: typeof WarrantyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cham-cong': {
      id: '/cham-cong'
      path: '/cham-cong'
      fullPath: '/cham-cong'
      preLoaderRoute: typeof ChamCongRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/_userLayout': {
      id: '/u/_userLayout'
      path: ''
      fullPath: '/u'
      preLoaderRoute: typeof UUserLayoutRouteImport
      parentRoute: typeof URoute
    }
    '/e/_employeeLayout': {
      id: '/e/_employeeLayout'
      path: ''
      fullPath: '/e'
      preLoaderRoute: typeof EEmployeeLayoutRouteImport
      parentRoute: typeof ERoute
    }
    '/admin/_reportLayout': {
      id: '/admin/_reportLayout'
      path: ''
      fullPath: '/admin'
      preLoaderRoute: typeof AdminReportLayoutRouteImport
      parentRoute: typeof AdminRoute
    }
    '/u/_userLayout/login': {
      id: '/u/_userLayout/login'
      path: '/login'
      fullPath: '/u/login'
      preLoaderRoute: typeof UUserLayoutLoginRouteImport
      parentRoute: typeof UUserLayoutRoute
    }
    '/u/_userLayout/_dashboardLayout': {
      id: '/u/_userLayout/_dashboardLayout'
      path: ''
      fullPath: '/u'
      preLoaderRoute: typeof UUserLayoutDashboardLayoutRouteImport
      parentRoute: typeof UUserLayoutRoute
    }
    '/e/_employeeLayout/login': {
      id: '/e/_employeeLayout/login'
      path: '/login'
      fullPath: '/e/login'
      preLoaderRoute: typeof EEmployeeLayoutLoginRouteImport
      parentRoute: typeof EEmployeeLayoutRoute
    }
    '/e/_employeeLayout/_dashboardLayout': {
      id: '/e/_employeeLayout/_dashboardLayout'
      path: ''
      fullPath: '/e'
      preLoaderRoute: typeof EEmployeeLayoutDashboardLayoutRouteImport
      parentRoute: typeof EEmployeeLayoutRoute
    }
    '/admin/_reportLayout/kiotviet': {
      id: '/admin/_reportLayout/kiotviet'
      path: '/kiotviet'
      fullPath: '/admin/kiotviet'
      preLoaderRoute: typeof AdminReportLayoutKiotvietRouteImport
      parentRoute: typeof AdminReportLayoutRoute
    }
    '/admin/_reportLayout/dahahi': {
      id: '/admin/_reportLayout/dahahi'
      path: '/dahahi'
      fullPath: '/admin/dahahi'
      preLoaderRoute: typeof AdminReportLayoutDahahiRouteImport
      parentRoute: typeof AdminReportLayoutRoute
    }
    '/u/_userLayout/_dashboardLayout/': {
      id: '/u/_userLayout/_dashboardLayout/'
      path: '/'
      fullPath: '/u/'
      preLoaderRoute: typeof UUserLayoutDashboardLayoutIndexRouteImport
      parentRoute: typeof UUserLayoutDashboardLayoutRoute
    }
    '/e/_employeeLayout/_dashboardLayout/': {
      id: '/e/_employeeLayout/_dashboardLayout/'
      path: '/'
      fullPath: '/e/'
      preLoaderRoute: typeof EEmployeeLayoutDashboardLayoutIndexRouteImport
      parentRoute: typeof EEmployeeLayoutDashboardLayoutRoute
    }
    '/u/_userLayout/_dashboardLayout/shift-slots': {
      id: '/u/_userLayout/_dashboardLayout/shift-slots'
      path: '/shift-slots'
      fullPath: '/u/shift-slots'
      preLoaderRoute: typeof UUserLayoutDashboardLayoutShiftSlotsRouteImport
      parentRoute: typeof UUserLayoutDashboardLayoutRoute
    }
    '/u/_userLayout/_dashboardLayout/shift-slot-types': {
      id: '/u/_userLayout/_dashboardLayout/shift-slot-types'
      path: '/shift-slot-types'
      fullPath: '/u/shift-slot-types'
      preLoaderRoute: typeof UUserLayoutDashboardLayoutShiftSlotTypesRouteImport
      parentRoute: typeof UUserLayoutDashboardLayoutRoute
    }
    '/u/_userLayout/_dashboardLayout/settings': {
      id: '/u/_userLayout/_dashboardLayout/settings'
      path: '/settings'
      fullPath: '/u/settings'
      preLoaderRoute: typeof UUserLayoutDashboardLayoutSettingsRouteImport
      parentRoute: typeof UUserLayoutDashboardLayoutRoute
    }
    '/u/_userLayout/_dashboardLayout/leave-requests': {
      id: '/u/_userLayout/_dashboardLayout/leave-requests'
      path: '/leave-requests'
      fullPath: '/u/leave-requests'
      preLoaderRoute: typeof UUserLayoutDashboardLayoutLeaveRequestsRouteImport
      parentRoute: typeof UUserLayoutDashboardLayoutRoute
    }
    '/u/_userLayout/_dashboardLayout/departments': {
      id: '/u/_userLayout/_dashboardLayout/departments'
      path: '/departments'
      fullPath: '/u/departments'
      preLoaderRoute: typeof UUserLayoutDashboardLayoutDepartmentsRouteImport
      parentRoute: typeof UUserLayoutDashboardLayoutRoute
    }
    '/u/_userLayout/_dashboardLayout/branchs': {
      id: '/u/_userLayout/_dashboardLayout/branchs'
      path: '/branchs'
      fullPath: '/u/branchs'
      preLoaderRoute: typeof UUserLayoutDashboardLayoutBranchsRouteImport
      parentRoute: typeof UUserLayoutDashboardLayoutRoute
    }
    '/e/_employeeLayout/_dashboardLayout/tasks': {
      id: '/e/_employeeLayout/_dashboardLayout/tasks'
      path: '/tasks'
      fullPath: '/e/tasks'
      preLoaderRoute: typeof EEmployeeLayoutDashboardLayoutTasksRouteImport
      parentRoute: typeof EEmployeeLayoutDashboardLayoutRoute
    }
    '/e/_employeeLayout/_dashboardLayout/shift-slots': {
      id: '/e/_employeeLayout/_dashboardLayout/shift-slots'
      path: '/shift-slots'
      fullPath: '/e/shift-slots'
      preLoaderRoute: typeof EEmployeeLayoutDashboardLayoutShiftSlotsRouteImport
      parentRoute: typeof EEmployeeLayoutDashboardLayoutRoute
    }
    '/e/_employeeLayout/_dashboardLayout/settings': {
      id: '/e/_employeeLayout/_dashboardLayout/settings'
      path: '/settings'
      fullPath: '/e/settings'
      preLoaderRoute: typeof EEmployeeLayoutDashboardLayoutSettingsRouteImport
      parentRoute: typeof EEmployeeLayoutDashboardLayoutRoute
    }
    '/e/_employeeLayout/_dashboardLayout/leave-requests': {
      id: '/e/_employeeLayout/_dashboardLayout/leave-requests'
      path: '/leave-requests'
      fullPath: '/e/leave-requests'
      preLoaderRoute: typeof EEmployeeLayoutDashboardLayoutLeaveRequestsRouteImport
      parentRoute: typeof EEmployeeLayoutDashboardLayoutRoute
    }
    '/e/_employeeLayout/_dashboardLayout/change-shift-requests': {
      id: '/e/_employeeLayout/_dashboardLayout/change-shift-requests'
      path: '/change-shift-requests'
      fullPath: '/e/change-shift-requests'
      preLoaderRoute: typeof EEmployeeLayoutDashboardLayoutChangeShiftRequestsRouteImport
      parentRoute: typeof EEmployeeLayoutDashboardLayoutRoute
    }
    '/u/_userLayout/_dashboardLayout/user-admins/': {
      id: '/u/_userLayout/_dashboardLayout/user-admins/'
      path: '/user-admins'
      fullPath: '/u/user-admins'
      preLoaderRoute: typeof UUserLayoutDashboardLayoutUserAdminsIndexRouteImport
      parentRoute: typeof UUserLayoutDashboardLayoutRoute
    }
    '/u/_userLayout/_dashboardLayout/tasks/': {
      id: '/u/_userLayout/_dashboardLayout/tasks/'
      path: '/tasks'
      fullPath: '/u/tasks'
      preLoaderRoute: typeof UUserLayoutDashboardLayoutTasksIndexRouteImport
      parentRoute: typeof UUserLayoutDashboardLayoutRoute
    }
    '/u/_userLayout/_dashboardLayout/employees/': {
      id: '/u/_userLayout/_dashboardLayout/employees/'
      path: '/employees'
      fullPath: '/u/employees'
      preLoaderRoute: typeof UUserLayoutDashboardLayoutEmployeesIndexRouteImport
      parentRoute: typeof UUserLayoutDashboardLayoutRoute
    }
    '/u/_userLayout/_dashboardLayout/user-admins/$id': {
      id: '/u/_userLayout/_dashboardLayout/user-admins/$id'
      path: '/user-admins/$id'
      fullPath: '/u/user-admins/$id'
      preLoaderRoute: typeof UUserLayoutDashboardLayoutUserAdminsIdRouteImport
      parentRoute: typeof UUserLayoutDashboardLayoutRoute
    }
    '/u/_userLayout/_dashboardLayout/tasks/pending-approvel': {
      id: '/u/_userLayout/_dashboardLayout/tasks/pending-approvel'
      path: '/tasks/pending-approvel'
      fullPath: '/u/tasks/pending-approvel'
      preLoaderRoute: typeof UUserLayoutDashboardLayoutTasksPendingApprovelRouteImport
      parentRoute: typeof UUserLayoutDashboardLayoutRoute
    }
    '/u/_userLayout/_dashboardLayout/employees/$id': {
      id: '/u/_userLayout/_dashboardLayout/employees/$id'
      path: '/employees/$id'
      fullPath: '/u/employees/$id'
      preLoaderRoute: typeof UUserLayoutDashboardLayoutEmployeesIdRouteImport
      parentRoute: typeof UUserLayoutDashboardLayoutRoute
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChamCongRoute: ChamCongRoute,
  WarrantyRoute: WarrantyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
